version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: grupo7-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - grupo7-network

volumes:
  redis_data:

networks:
  grupo7-network:
    driver: bridge 